### ISSUE TITLE
Inicar o template com <Routes> no App.tsx

### ISSUE THREAD

**Issue by raulmelo** [AgathosDev/cra-template-agathos#1]
Gostei do template e estou usando nos meus projetos pessoais, fácil e simples de configurar, so tenho algumas sugestões, se quiser posso fazer um _Fork_ para avaliar meu _pull request_

Iniciar o projeto já com as rotas configuradas.

Atualmente só existe o arquivo de Rota porem não esta setado no 
**_*cra-template-agathos/template/src/App.tsx*_**

```js
const App: React.FC = () => {
  return <Route />;
};
```

Adicionar o **_< Router history={hist} >_**
**_cra-template-agathos/template/src/routes.tsx_**

```js
<Router history={hist}>
 <Switch>
    <Route path="/" component={Home} exact />
  </Switch>
</Router>
```

**Comment by melquisedecfelipe** [comment]
Obrigado pela indicação.

Podemos adicionar sim, mas eu utilizaria os novos hooks do React Router, o que acha @raulmelo?

**Comment by raulmelo** [comment]
Acho bom e pratico!

Continuarei usando seu template que esta bem completo.

**Comment by melquisedecfelipe** [comment]
@raulmelo acabei de atualizar, o NPM e o Git, quando quiser poder abrir uma PR.

Muito obrigado pela indicação de melhoria! :100:
